apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  creationTimestamp: "2025-08-18T20:44:54Z"
  generation: 2
  labels:
    kueue.x-k8s.io/queue-name: multislice-queue
    xpk.google.com/workload: suj-pw-llama3--1-n24
  name: suj-pw-llama3--1-n24
  namespace: default
spec:
  coordinator:
    replicatedJob: pathways-head
  failurePolicy:
    restartStrategy: Recreate
  network:
    enableDNSHostnames: true
    publishNotReadyAddresses: true
  replicatedJobs:
  - name: pathways-head
    replicas: 1
    template:
      metadata:
        annotations:
          alpha.jobset.sigs.k8s.io/exclusive-topology: kubernetes.io/hostname
      spec:
        backoffLimit: 0
        completionMode: Indexed
        completions: 1
        parallelism: 1
        template:
          metadata:
            labels:
              kueue.x-k8s.io/podset: pathways-head
          spec:
            containers:
            - command:
              - bash
              - -c
              - |
                echo XPK Start: $(date);
                _sigterm() (kill -SIGTERM $! 2>/dev/null;);
                trap _sigterm SIGTERM;

                (export TPU_STDERR_LOG_LEVEL=0 && export TPU_MIN_LOG_LEVEL=0 && export TF_CPP_MIN_LOG_LEVEL=0 && export TPU_VMODULE=real_program_continuator=1 &&    export ENABLE_PATHWAYS_PERSISTENCE=1 && export JAX_PLATFORMS=proxy && export ENABLE_PJRT_COMPATIBILITY=true &&  python3 add_one_col_py.py) & PID=$!;
                while kill -0 $PID 2>/dev/null;
                    do sleep 5;
                done;
                wait $PID;
                EXIT_CODE=$?;

                echo XPK End: $(date);
                echo EXIT_CODE=$EXIT_CODE;


                exit $EXIT_CODE
              env:
              - name: PATHWAYS_HEAD
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.labels['jobset.sigs.k8s.io/coordinator']
              - name: JAX_PLATFORMS
                value: proxy
              - name: XCLOUD_ENVIRONMENT
                value: GCP
              - name: JAX_BACKEND_TARGET
                value: grpc://$(PATHWAYS_HEAD):29000
              image: gcr.io/cloud-tpu-multipod-dev/sujinesh_maxtext_latest
              # image: python3.10-slim-bullseye
              imagePullPolicy: Always
              name: jax-tpu
              resources:
                limits:
                  cpu: "24"
                  memory: 100G
              securityContext:
                privileged: true
              volumeMounts:
              - mountPath: /tmp
                name: shared-tmp
            dnsPolicy: ClusterFirstWithHostNet
            hostNetwork: true
            initContainers:
            - args:
              - --server_port=29001
              - --gcs_scratch_location=gs://sujinesh-cloud-tpu-multipod-dev-us
              - --node_type=resource_manager
              - --instance_count=1
              - --instance_type=tpuv5e:4x8
              - --xla_tpu_use_enhanced_launch_barrier=true
              - --logtostderr
              - --stderrthreshold=0
              - --v=1
              env:
              - name: REPLICATED_JOB_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['jobset.sigs.k8s.io/replicatedjob-name']
              - name: JOBSET_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['jobset.sigs.k8s.io/jobset-name']
              - name: HOST_ADDRESS
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.labels['jobset.sigs.k8s.io/coordinator']
              - name: TPU_SKIP_MDS_QUERY
                value: "true"
              image: us-docker.pkg.dev/cloud-tpu-v2-images-dev/pathways/gke/ksadi/unsanitized_server_maxtext:latest
              imagePullPolicy: Always
              name: pathways-rm
              ports:
              - containerPort: 29001
                protocol: TCP
              - containerPort: 29002
                protocol: TCP
              resources:
                limits:
                  cpu: "8"
                  memory: 16G
              restartPolicy: Always
            - args:
              - --server_port=29000
              - --resource_manager_address=$(PATHWAYS_HEAD):29001
              - --gcs_scratch_location=gs://sujinesh-cloud-tpu-multipod-dev-us
              - --xla_tpu_scoped_vmem_limit_kib=98304
              - --xla_tpu_use_minor_sharding_for_major_trivial_input=true
              - --xla_tpu_relayout_group_size_threshold_for_reduce_scatter=1
              - --xla_tpu_assign_all_reduce_scatter_layout=true
              - --xla_tpu_enable_data_parallel_all_reduce_opt=true
              - --xla_tpu_data_parallel_opt_different_sized_ops=true
              - --xla_tpu_enable_async_collective_fusion=true
              - --xla_tpu_enable_async_collective_fusion_fuse_all_gather=true
              - --xla_tpu_enable_async_collective_fusion_multiple_steps=true
              - --xla_tpu_overlap_compute_collective_tc=true
              - --xla_enable_async_all_gather=true
              - --xla_tpu_enable_async_collective_fusion_fuse_all_reduce=false
              - --xla_tpu_enable_sparse_core_collective_offload_all_reduce=true
              - --xla_tpu_enable_all_reduce_offload_tracing=true
              - --xla_tpu_use_tc_device_shape_on_sc=true
              - --xla_sc_enable_instruction_fusion=false
              - --xla_sc_disjoint_spmem=false
              - --xla_sc_disable_megacore_partitioning=true
              - --xla_tpu_enable_all_experimental_scheduler_features=true
              - --xla_tpu_enable_scheduler_memory_pressure_tracking=true
              - --xla_tpu_host_transfer_overlap_limit=24
              - --xla_tpu_aggressive_opt_barrier_removal=ENABLED
              - --xla_lhs_prioritize_async_depth_over_stall=ENABLED
              - --xla_tpu_enable_ag_backward_pipelining=true
              - --xla_should_allow_loop_variant_parameter_in_chain=ENABLED
              - --xla_should_add_loop_invariant_op_in_chain=ENABLED
              - --xla_max_concurrent_host_send_recv=100
              - --xla_tpu_scheduler_percent_shared_memory_limit=100
              - --xla_latency_hiding_scheduler_rerun=2
              - --xla_tpu_use_enhanced_launch_barrier=true
              env:
              - name: PATHWAYS_HEAD
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.labels['jobset.sigs.k8s.io/coordinator']
              image: us-docker.pkg.dev/cloud-tpu-v2-images-dev/pathways/gke/ksadi/unsanitized_proxy_server_maxtext:latest
              imagePullPolicy: Always
              name: pathways-proxy
              ports:
              - containerPort: 29000
                protocol: TCP
              resources:
                limits:
                  cpu: "16"
                  memory: 100G
              restartPolicy: Always
            nodeSelector:
              cloud.google.com/gke-nodepool: cpu-np
            restartPolicy: Never
            volumes:
            - hostPath:
                path: /tmp
                type: DirectoryOrCreate
              name: shared-tmp
  - name: worker
    replicas: 1
    template:
      metadata: {}
      spec:
        backoffLimit: 32
        completionMode: Indexed
        completions: 8
        parallelism: 8
        template:
          metadata:
            annotations:
              alpha.jobset.sigs.k8s.io/exclusive-topology: cloud.google.com/gke-nodepool
            labels:
              kueue.x-k8s.io/podset: worker
          spec:
            containers:
            - args:
              - --server_port=29005
              - --resource_manager_address=$(PATHWAYS_HEAD):29001
              - --gcs_scratch_location=gs://sujinesh-cloud-tpu-multipod-dev-us
              - --xla_tpu_use_enhanced_launch_barrier=true
              - --logtostderr
              - --stderrthreshold=0
              - --v=1
              env:
              - name: TPU_MIN_LOG_LEVEL
                value: "0"
              - name: TF_CPP_MIN_LOG_LEVEL
                value: "0"
              - name: XCLOUD_ENVIRONMENT
                value: GCP
              - name: MEGASCALE_GRPC_ENABLE_XOR_TRACER
                value: "false"
              - name: MEGASCALE_NUM_SLICES
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.labels['jobset.sigs.k8s.io/replicatedjob-replicas']
              - name: JOBSET_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['jobset.sigs.k8s.io/jobset-name']
              - name: REPLICATED_JOB_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['jobset.sigs.k8s.io/replicatedjob-name']
              - name: MEGASCALE_SLICE_ID
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.labels['jobset.sigs.k8s.io/job-index']
              - name: PATHWAYS_HEAD
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.labels['jobset.sigs.k8s.io/coordinator']
              - name: MEGASCALE_COORDINATOR_ADDRESS
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.labels['jobset.sigs.k8s.io/coordinator']
              image: us-docker.pkg.dev/cloud-tpu-v2-images-dev/pathways/gke/ksadi/unsanitized_server_maxtext:latest
              imagePullPolicy: Always
              name: pathways-worker
              ports:
              - containerPort: 29005
                protocol: TCP
              - containerPort: 29006
                protocol: TCP
              - containerPort: 8471
                protocol: TCP
              - containerPort: 8080
                protocol: TCP
              resources:
                limits:
                  google.com/tpu: "4"
              volumeMounts:
              - mountPath: /tmp
                name: shared-tmp
            dnsPolicy: ClusterFirstWithHostNet
            hostNetwork: true
            initContainers:
            - env:
              - name: GRPC_SERVER_ADDRESS
                value: '''0.0.0.0:50051'''
              image: gcr.io/cloud-tpu-multipod-dev/ksadi_sidecar_maxtext:latest
              imagePullPolicy: Always
              name: colocated-python-sidecar
              ports:
              - containerPort: 50051
                protocol: TCP
              resources: {}
              restartPolicy: Always
              volumeMounts:
              - mountPath: /tmp
                name: shared-tmp
            nodeSelector:
              cloud.google.com/gke-tpu-accelerator: tpu-v5-lite-podslice
              cloud.google.com/gke-tpu-topology: 4x8
            priorityClassName: medium
            restartPolicy: OnFailure
            terminationGracePeriodSeconds: 300
            volumes:
            - hostPath:
                path: /tmp
                type: DirectoryOrCreate
              name: shared-tmp
  startupPolicy:
    startupPolicyOrder: InOrder
  successPolicy:
    operator: All
    targetReplicatedJobs:
    - pathways-head
  suspend: false
status:
  conditions:
  - lastTransitionTime: "2025-08-18T20:45:48Z"
    message: jobset is resumed
    reason: ResumeJobs
    status: "False"
    type: Suspended
  - lastTransitionTime: "2025-08-18T20:46:59Z"
    message: in order startup policy is in progress
    reason: InOrderStartupPolicyInProgress
    status: "True"
    type: StartupPolicyInProgress
  - lastTransitionTime: "2025-08-18T20:45:48Z"
    message: in order startup policy has completed
    reason: InOrderStartupPolicyCompleted
    status: "False"
    type: StartupPolicyCompleted
  replicatedJobsStatus:
  - active: 1
    failed: 0
    name: worker
    ready: 1
    succeeded: 0
    suspended: 0
  - active: 1
    failed: 0
    name: pathways-head
    ready: 0
    succeeded: 0
    suspended: 0

